### ISSUE TITLE
Move artifacts as Bintray is going offline

### ISSUE THREAD

**Issue by ollyw** [svroonland/zio-amqp#110]
Hi, it seems that Bintray will stop operation on 1st of May, and stopping new submissions sooner. It would be good to get this library onto other artefact repo before that happens. https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by svroonland** [comment]
No worries, will do so well before May 1st. Already migrated two other projects to Sonatype, so it should not be a problem.

Thanks for the heads up still!

**Comment by svroonland** [comment]
@ollyw v0.1.5 should be available from Sonatype now.

**Comment by ollyw** [comment]
Thank you very much!
