### ISSUE TITLE
Upgrade to ZIO 2.0

### ISSUE THREAD

**Issue by swoogles** [svroonland/zio-amqp#172]
ZIO 2.0 is at Milestone 4, with an RC expected in the next few weeks.
https://github.com/zio/zio/releases/tag/v2.0.0-M4

The API is nearly stable at this point, so any early migration work against this version should pay off towards the official 2.0 release.

The progress is being tracked here:
zio/zio#5470

The Stream Encoding work in progress is the only area where the API might still change before the RC.

We are actively working on a ScalaFix rule that will cover the bulk of the simple API changes:
https://github.com/zio/zio/blob/series/2.x/scalafix/rules/src/main/scala/fix/Zio2Upgrade.scala
We highly recommend starting with that, and then working through any remaining compilation errors :)

To assist with the rest of the migration, we have created this guide:
https://zio.dev/howto/migrate/zio-2.x-migration-guide/

If you would like assistance with the migration from myself or other ZIO contributors, please let us know!

**Comment by svroonland** [comment]
ZIO 2.0.0-RC1 is out now, would be nice to do another update.

**Comment by yisraelU** [comment]
@svroonland yes, will do

**Comment by svroonland** [comment]
Awesome, thanks!

**Comment by yisraelU** [comment]
@svroonland 2.12 and 2.13 compile nicely with the new version RC1, however scala 3 compilation is throwing errors I am not familiar with (there are 32 of them).
``` [info] compiling 6 Scala sources to /home/yunion/IdeaProjects/zio-amqp/target/scala-3.0.1/classes ...
[error] error while loading $throws$package$,
[error] class file scala/runtime/$throws$package.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
[error] TASTy signature has wrong version.
[error]  expected: {majorVersion: 28, minorVersion: 0}
[error]  found   : {majorVersion: 28, minorVersion: 1}
[error] ```

 Do you know what these are ?

**Comment by svroonland** [comment]
Yeah I think I ran into that when using scala version 3.0.1, which is not compatible with 3.1. which is what ZIO is compiled against. It is fixed by upgrading to 3.1, including in the CircleCI config, like here https://github.com/svroonland/rezilience/pull/153/commits/f276d33d9299c53d26b4c90254dff0e6e361261d

**Comment by ianpojman** [comment]
Hi, could we get a release for 2.0.0 final?

**Comment by svroonland** [comment]
@ianpojman Here you go https://github.com/svroonland/zio-amqp/releases/tag/v0.4.0
