### ISSUE TITLE
AMQP1.0 support

### ISSUE THREAD

**Issue by mtumilowicz** [svroonland/zio-amqp#290]
Hi, I would like to ask if AMQP1.0 is supported by this library?
In config class I don't see any place where you could choose AMQP version
```
case class AMQPConfig(
  user: String,
  password: String,
  vhost: String,
  heartbeatInterval: Duration,
  ssl: Boolean,
  host: String,
  port: Short,
  connectionTimeout: Duration
)
```

**Comment by svroonland** [comment]
Hi @mtumilowicz, I'm not sure. zio-amqp depends on com.rabbitmq.amqp-client v5.16.0, you'd have to check if that supports AMQP 1.0
