### ISSUE TITLE
Add e.g Apache License (and publish to Maven)

### ISSUE THREAD

**Issue by Cereopsis** [svroonland/zio-amqp#32]
I realise this is in its early stages but as there doesn't appear to be an artefact on Maven it would be nice to use the sources directly by including them in a build but of course with proper attribution :-)

**Comment by svroonland** [comment]
@Cereopsis Done! Added an Apache license and updated the readme with how to get the artifact. 

It was already available, but a `resolver +=` was necessary, which was not in the readme.
